### ISSUE TITLE
add st command to display current configuration of apps/services

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Tooling#64]
Currently, one must peek into the `steeltoe.yml` file. 

E.g.
```
% cat steeltoe.yml
apps: {}
services:
  mydb:
    type: postgresql
    deployArgs: {}
```

Adding a command to prettify the contents to a console would be helpful and also decouple a user from having to know `st` storage format.

Perhaps something like:
```
% st show
Name               Type
mydb               postgresql
```
